database:
  user: hanko
  password: hanko
  host: localhost
  port: 5432
  dialect: postgres
passcode:
  email:
    from_address: no-reply@hanko.io
  smtp:
    host: localhost
    port: 2500
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
webauthn:
  relying_party:
    origin: http://localhost:63342
server:
  public:
    cors:
      enabled: true
      allow_credentials: true
      allow_origins:
        - http://localhost:63342
      allow_methods:
session:
  privileged_lifespan: "10m"
  cookie:
    secure: false

password:
  enabled: true
emails:
  require_verification: true
